apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
spec:
  replicas: 0
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
        - image: dtr.demo.mirantis.com/launch-party/pacman-nodejs:latest
          name: pacman
          ports:
            - containerPort: 8080
              name: http-server
